create table if not exists public.saved_tweets (
  id bigint generated by default as identity primary key,
  text text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
